Ui updates
hps/heartland-gravity-forms-addon pull request #22
Opened 2016-11-22 18:03 UTC by makenziemoore

-update styles
-add documentation / banner image / icon for WP plugin

2016-11-28 16:23 UTC, slogsdon requested changes
I'd prefer if `classes/class-gf-field-hpscreditcard.php` received more love: make coding style more inline with the rest of our plugin, move embedded HTML to template files, etc.

2016-11-28 16:23 UTC, slogsdon commented on assets/js/securesubmit.js
> +console.log('hello');
This line should be removed.

2016-11-28 16:23 UTC, slogsdon commented on classes/class-gf-field-hpscreditcard.php
> +	}
This method isn't required and should be removed

2016-11-28 16:23 UTC, slogsdon commented on classes/class-gf-field-hpscreditcard.php
> +	}
This method isn't required and should be removed

2016-11-28 16:23 UTC, slogsdon commented on classes/class-gf-securesubmit.php
> +      echo '<script>console.log("hello") </script>';
This line should be removed.

2016-11-28 19:18 UTC, ttnnkkrr commented
@slogsdon OK i deleted the stuff you referenced

2016-11-28 19:20 UTC, slogsdon commented
@ttnnkkrr There's leftover PHP that will cause a ParseError: https://github.com/hps/heartland-gravity-forms-addon/blob/628f1cbc3548237d977c94f26c27e65e7da4be57/classes/class-gf-field-hpscreditcard.php#L57-L63

2016-11-28 19:21 UTC, slogsdon commented
@ttnnkkrr Also, don't forget about giving more love on `classes/class-gf-field-hpscreditcard.php`

2017-01-05 16:05 UTC, slogsdon commented
@makenziemoore @ttnnkkrr I see a bunch of warnings when dragging the new CC field into a form for use:

```
[Thu Jan  5 11:03:39 2017] PHP Notice:  Undefined variable: action in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 170
[Thu Jan  5 11:03:39 2017] PHP Stack trace:
[Thu Jan  5 11:03:39 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:0
[Thu Jan  5 11:03:39 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:91
[Thu Jan  5 11:03:39 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:03:39 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:03:39 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   6. GFForms::add_field() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   7. GFFormDetail::add_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3658
[Thu Jan  5 11:03:39 2017] PHP   8. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:2749
[Thu Jan  5 11:03:39 2017] PHP   9. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:03:39 2017] PHP  10. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:03:39 2017] PHP  11. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:03:39 2017] PHP Notice:  Undefined variable: action in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 171
[Thu Jan  5 11:03:39 2017] PHP Stack trace:
[Thu Jan  5 11:03:39 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:0
[Thu Jan  5 11:03:39 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:91
[Thu Jan  5 11:03:39 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:03:39 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:03:39 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   6. GFForms::add_field() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   7. GFFormDetail::add_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3658
[Thu Jan  5 11:03:39 2017] PHP   8. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:2749
[Thu Jan  5 11:03:39 2017] PHP   9. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:03:39 2017] PHP  10. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:03:39 2017] PHP  11. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:03:39 2017] PHP Notice:  Undefined variable: card in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 178
[Thu Jan  5 11:03:39 2017] PHP Stack trace:
[Thu Jan  5 11:03:39 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:0
[Thu Jan  5 11:03:39 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:91
[Thu Jan  5 11:03:39 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:03:39 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:03:39 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   6. GFForms::add_field() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   7. GFFormDetail::add_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3658
[Thu Jan  5 11:03:39 2017] PHP   8. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:2749
[Thu Jan  5 11:03:39 2017] PHP   9. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:03:39 2017] PHP  10. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:03:39 2017] PHP  11. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:03:39 2017] PHP Notice:  Undefined variable: expiration_month in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 213
[Thu Jan  5 11:03:39 2017] PHP Stack trace:
[Thu Jan  5 11:03:39 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:0
[Thu Jan  5 11:03:39 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:91
[Thu Jan  5 11:03:39 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:03:39 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:03:39 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   6. GFForms::add_field() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:03:39 2017] PHP   7. GFFormDetail::add_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3658
[Thu Jan  5 11:03:39 2017] PHP   8. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:2749
[Thu Jan  5 11:03:39 2017] PHP   9. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:03:39 2017] PHP  10. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:03:39 2017] PHP  11. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:03:39 2017] PHP Warning:  Missing argument 2 for GF_Field_HPSCreditCard::get_expiration_months(), called in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 213 and defined in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 248
[Thu Jan  5 11:03:39 2017] PHP Stack trace:
[Thu Jan  5 11:03:39 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:0
[Thu Jan  5 11:03:39 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin-ajax.php:91
[Thu Jan  5 11:03:39 2017] PHP   3. WP_Hook->do_action() /Us [...]

2017-01-05 16:06 UTC, slogsdon commented
@makenziemoore @ttnnkkrr Can we make the default title for the Secure CC fields something other than 'Untitled'?

2017-01-05 16:13 UTC, slogsdon commented
@makenziemoore @ttnnkkrr A few items:

Can we make it so the fields within the Secure CC field group are disabled when editing the form?

![screen shot 2017-01-05 at 11 08 46 am](https://cloud.githubusercontent.com/assets/647624/21687515/8b2b8f44-d337-11e6-8f37-381816c26968.png)

The CC image bar seems to overflow onto the builtin credit card field group:

![screen shot 2017-01-05 at 11 09 08 am](https://cloud.githubusercontent.com/assets/647624/21687527/9b75ec46-d337-11e6-8431-a130ba1e9c75.png)

What do the 'Supported Card Types' checkboxes do? When I click them, I'm not sure what they do.

2017-01-05 16:18 UTC, slogsdon commented
@makenziemoore @ttnnkkrr I also get warnings when I click 'Update Form' with the Secure CC field group in the form:

```
[Thu Jan  5 11:17:04 2017] PHP Warning:  Invalid argument supplied for foreach() in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 347
[Thu Jan  5 11:17:04 2017] PHP Stack trace:
[Thu Jan  5 11:17:04 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin.php:0
[Thu Jan  5 11:17:04 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin.php:222
[Thu Jan  5 11:17:04 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:17:04 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:17:04 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   6. GFForms::forms() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   7. GFForms::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3310
[Thu Jan  5 11:17:04 2017] PHP   8. GFFormDetail::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:2901
[Thu Jan  5 11:17:04 2017] PHP   9. GFCommon::gf_vars() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:54
[Thu Jan  5 11:17:04 2017] PHP  10. GFCommon::get_merge_tags() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:3898
[Thu Jan  5 11:17:04 2017] PHP  11. GFCommon::get_field_merge_tags() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:538
[Thu Jan  5 11:17:04 2017] PHP  12. GF_Field_HPSCreditCard->get_entry_inputs() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:619
[Thu Jan  5 11:17:04 2017] PHP Warning:  Invalid argument supplied for foreach() in /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php on line 631
[Thu Jan  5 11:17:04 2017] PHP Stack trace:
[Thu Jan  5 11:17:04 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin.php:0
[Thu Jan  5 11:17:04 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin.php:222
[Thu Jan  5 11:17:04 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:17:04 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:17:04 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   6. GFForms::forms() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   7. GFForms::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3310
[Thu Jan  5 11:17:04 2017] PHP   8. GFFormDetail::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:2901
[Thu Jan  5 11:17:04 2017] PHP   9. GFCommon::gf_vars() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:54
[Thu Jan  5 11:17:04 2017] PHP  10. GFCommon::get_merge_tags() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:3898
[Thu Jan  5 11:17:04 2017] PHP  11. GFCommon::get_field_merge_tags() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:538
[Thu Jan  5 11:17:04 2017] PHP Notice:  Undefined variable: action in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 170
[Thu Jan  5 11:17:04 2017] PHP Stack trace:
[Thu Jan  5 11:17:04 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin.php:0
[Thu Jan  5 11:17:04 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin.php:222
[Thu Jan  5 11:17:04 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:17:04 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:17:04 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   6. GFForms::forms() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   7. GFForms::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3310
[Thu Jan  5 11:17:04 2017] PHP   8. GFFormDetail::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:2901
[Thu Jan  5 11:17:04 2017] PHP   9. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:408
[Thu Jan  5 11:17:04 2017] PHP  10. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:17:04 2017] PHP  11. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:17:04 2017] PHP  12. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:17:04 2017] PHP Notice:  Undefined variable: action in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 171
[Thu Jan  5 11:17:04 2017] PHP Stack trace:
[Thu Jan  5 11:17:04 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin.php:0
[Thu Jan  5 11:17:04 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin.php:222
[Thu Jan  5 11:17:04 2017] PHP   3. WP_Hook->do_action() /Users/shane.logsdon/wordpress/wp-includes/plugin.php:453
[Thu Jan  5 11:17:04 2017] PHP   4. WP_Hook->apply_filters() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:323
[Thu Jan  5 11:17:04 2017] PHP   5. call_user_func_array:{/Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298}() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   6. GFForms::forms() /Users/shane.logsdon/wordpress/wp-includes/class-wp-hook.php:298
[Thu Jan  5 11:17:04 2017] PHP   7. GFForms::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:3310
[Thu Jan  5 11:17:04 2017] PHP   8. GFFormDetail::forms_page() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/gravityforms.php:2901
[Thu Jan  5 11:17:04 2017] PHP   9. GFFormDisplay::get_field() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_detail.php:408
[Thu Jan  5 11:17:04 2017] PHP  10. GFFormDisplay::get_field_content() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2786
[Thu Jan  5 11:17:04 2017] PHP  11. GFCommon::get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/form_display.php:2847
[Thu Jan  5 11:17:04 2017] PHP  12. GF_Field_HPSCreditCard->get_field_input() /Users/shane.logsdon/wordpress/wp-content/plugins/gravityforms/common.php:2805
[Thu Jan  5 11:17:04 2017] PHP Notice:  Undefined variable: card in /Users/shane.logsdon/wordpress/wp-content/plugins/heartland-secure-submit-addon-for-gravity-forms/classes/class-gf-field-hpscreditcard.php on line 178
[Thu Jan  5 11:17:04 2017] PHP Stack trace:
[Thu Jan  5 11:17:04 2017] PHP   1. {main}() /Users/shane.logsdon/wordpress/wp-admin/admin.php:0
[Thu Jan  5 11:17:04 2017] PHP   2. do_action() /Users/shane.logsdon/wordpress/wp-admin/admin.php:222
[Thu Ja [...]

2017-01-05 16:21 UTC, slogsdon commented
@makenziemoore @ttnnkkrr I thought the Secure CC field group was supposed to have the iframe version of our tokenization offering? I don't see that as a thing:

![screen shot 2017-01-05 at 11 19 37 am](https://cloud.githubusercontent.com/assets/647624/21687912/06eec3ac-d339-11e6-875f-4cd334d8c98c.png)

2017-01-05 16:25 UTC, slogsdon commented
@makenziemoore @ttnnkkrr Tab order is messed up as well. I see it going in this order with the credit card group in the form before the address:

1. Cardholder name
2. City
3. Card number
4. Expiration date
5. State
6. CVV
7. Zip
8. Country

2017-02-09 15:35 UTC, merged