Fixed: UI Glitch - on Secure Submit payment page
hps/heartland-gravity-forms-addon pull request #84
Opened 2024-07-02 07:57 UTC by mayur-vachchewar

2024-07-02 12:20 UTC, mayur-vachchewar commented
@MSmedal could you please review and approve this PR.

2024-07-09 19:42 UTC, MSmedal requested changes
All seems well! Please advise on the single housekeeping item I raised and we'll go from there.

2024-07-09 19:42 UTC, MSmedal commented on readme.txt
Are you testing on the latest version of WP? If so, please update line 4 also. I tested using 6.5.3 and it seems to work well

2024-07-10 10:11 UTC, mayur-vachchewar commented on readme.txt
@MSmedal yes, it tested upto 6.5.5.
For you reference: 
![Uploading image.png…]()

2024-07-10 12:17 UTC, MSmedal approved these changes

2024-07-16 12:42 UTC, merged